package ${packageName}.repository;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.stereotype.Repository;
import ${packageName}.model.${upperFirstLetterName};
import javax.annotation.Generated;

@Generated(
    value = {
        "Labor version:1.0.0"
    },
    comments = "This class is generated by Labor"
)
@Repository
public interface ${upperFirstLetterName}Repository extends PagingAndSortingRepository<${upperFirstLetterName}, ${primaryKeyType}> {

}
