package ${packageName}.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import springfox.documentation.annotations.ApiIgnore;
import javax.annotation.Generated;

@Generated(
    value = {
        "Labor version:1.0.0"
    },
    comments = "This class is generated by Labor"
)
@RestController
@ApiIgnore
public class IndexController {

	@RequestMapping(value="/index",method=RequestMethod.GET)
	public String index() {
		return "Congratulations. Your Application Is Available. ";
	}

}
